name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  my-cicd-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code  # ensures the workflow has access to the project files.
        uses: actions/checkout@v4


      - name: Set up Python # ensures that the required Python environment is available for running dependencies.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Find your Github Workspace Path
        run: env | grep RUNNER_WORKSPACE  # If no results are returned, then remove '| grep RUNNER_WORKSPACE' from the command. and run again as RUNNER_WORKSPACE in the past was also referred as GITHUB_WORKSPACE.


      - name: List the contents of Github workspace
        run: |
          echo "--------------------------------"
          ls -R $RUNNER_WORKSPACE

